#pragma once

#define USE_SERIAL

#define MASTER_LEFT

#define IGNORE_MOD_TAP_INTERRUPT

#define MOUSEKEY_INTERVAL           20
#define MOUSEKEY_DELAY              0
#define MOUSEKEY_TIME_TO_MAX        60
#define MOUSEKEY_WHEEL_MAX_SPEED    MOUSEKEY_MAX_SPEED
#define MOUSEKEY_WHEEL_TIME_TO_MAX  MOUSEKEY_TIME_TO_MAX

#define MOUSEKEY_WHEEL_DELAY 301

#define MOUSEKEY_MAX_SPEED 6

#define MOUSEKEY_WHEEL_INTERVAL 105
